### ISSUE TITLE
Download media

### ISSUE THREAD

**Issue by johnbradley** [Imageomics/pyMorphoSource#2]
Allow users to download files from morphosource.

**Comment by johnbradley** [comment]
The MorphoSource API has a [/api/download/{media-id}](https://morphosource.stoplight.io/docs/morphosource-api/stzmm22vruz2k-download-media-file) endpoint that requires quite a few parameters: use statement, use category, and agreements accepted flag. This endpoint also requires a user to pass a MorphoSource API key via the request header. The endpoint returns JSON with a `download_url` that also requires the MorphoSource API key in the header.

**Comment by johnbradley** [comment]
The `download_url` returns a zip file with multiple files instead of just the media file.
For example downloading media id `000010112` returns a zip file with the following layout:
![Screenshot 2023-10-17 at 8 11 34 AM](https://github.com/Imageomics/pyMorphoSource/assets/1024463/27005eaf-0b3d-47ce-9ffc-bab0fe5d1c62)

**Comment by johnbradley** [comment]
Some media a restricted and if approval hasn't been given the download_url will return a 404. In the JSON payload for these restricted media there is the following propery `'visibility': ['restricted_download']`. I don't think there is a way to request access via the API. I think the only option is to request access via the MorphoSource website, wait for permissions (if given) and then you can download.

**Comment by muratmaga** [comment]
> I don't think there is a way to request access via the API. I think the only option is to request access via the MorphoSource website,

Yes, this package/tool will be strictly for open-access datasets. Under their search, I believe this is indicated by the field "Publication Status" (see the screen capture). 
<img width="350" alt="image" src="https://github.com/Imageomics/pyMorphoSource/assets/21285140/e38556c7-9a5c-4885-a178-f6ffb568d40c">

**Comment by johnbradley** [comment]
Implemented by #5
