### ISSUE TITLE
Allow searching GBIF Taxonomy for media

### ISSUE THREAD

**Issue by johnbradley** [Imageomics/pyMorphoSource#8]
Users would like to search media for `Taxonomy (GBIF)` just like they can for physical objects.
This functionality isn't available in the MorphoSource API currently.

**Comment by johnbradley** [comment]
Example image for how this might be used:
<img width="641" alt="Screenshot 2023-10-31 at 2 36 19 PM" src="https://github.com/Imageomics/pyMorphoSource/assets/1024463/77674e55-b0a3-4726-ab88-efd6b693e6f8">

**Comment by johnbradley** [comment]
I spent some time looking through how this might be done with the current MorpoSource API.
In practice the API limits `per_page` to 1000 currently. Passing a larger value just returns a 1000 item page.
Searching media or biological specimens takes ~4 seconds no matter the `per_page` value.
Retrieving a single biological specimen with the GET API endpoint takes 1/2 a second, but the GBIF taxonomy isn't included in the payload so fetching a single biological specimen doesn't allow us to check the taxonomy.
So the only way to filter taxonomy is via the biological specimen endpoint.

**Comment by muratmaga** [comment]
> check the taxonomy.
> So the only way to filter taxonomy is via the biological specimen search endpoint.

Perhaps we should invite @JulieWinchester @MorphoSource to this conversation. I wonder a change at the API level is feasible.
